image: node:latest

stages:
  - build
  - test
  - deploy
  
services:
  - postgres:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install

# Build and compile
build:
  stage: build
  script:
    - npm run build


# Test components
test_comp:
  stage : test
  script:
    - npm run test

# Test database
test_db:
  stage : test
  script:
    - npm run test

# Deploy to heroku
deploy_heroku:
  stage : deploy
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=backend-drp38 --api-key=$JACK_HEROKU_API_KEY
  only:
    - master

