default: 
  image: node:latest
  
  before_script:
    - npm install
  
  services:
    - postgres:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

# Build and compile
build:
  stage: build
  script:
    - npm run build

# Test components
test:
  stage : test
  script:
    - npm run test

# Deploy to heroku
deploy_heroku:
  stage: deploy
  image: ruby:latest
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - master

