default:
  image: node:latest
  before_script:
    - npm install

build-job:
  stage: build
  script:
    - npm run build


test-job:
  stage: test
  script:
    - npm run test

deploy-prod:
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=backend-drp38 --api-key=$JACK_HEROKU_API_KEY